# Generated by Django 4.2.20 on 2025-03-11 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.TextField(default='London')),
                ('initiator', models.CharField(max_length=100)),
                ('guest', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('duration', models.DurationField()),
            ],
        ),
    ]
